### ISSUE TITLE
cool down time in between games

### ISSUE THREAD

**Issue by AdamSpannbauer** [AdamSpannbauer/rush#28]
there needs to be a little break in between games to avoid bad UX (if playing protect the center and you click right as game changes you might immediately lose the next game because of that click)

maybe #23 and this issue tie in together

**Comment by MarkHale94** [comment]
I was thinking about this the other day. Might make sense to combine this with [#23](https://github.com/AdamSpannbauer/rush/issues/23) as a kind of "animation" that shows win/loss and probably losing a life if you did lose. 

LOL should have read the description of this issue
